name: second

on:
  workflow_run:
    workflows: [first]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_CONCLUSION: ${{ github.event.workflow_run }}
    steps:
      - run: echo $WORKFLOW_CONCLUSION
      - run: echo "wat"