name: second

on:
  workflow_run:
    workflows: [first]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_VALUE: ${{ github.event.workflow_run.workflow_name }}
    steps:
      - run: echo $WORKFLOW_VALUE
      - run: echo "wat"