name: second

on:
  workflow_run:
    workflows: [first]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_NAME: ${{ github.event_name }}
      WORKFLOW_CONCLUSION: ${{ github.event.workflow_run.conclusion }}
    steps:
      - run: echo $WORKFLOW_NAME
      - run: echo $WORKFLOW_CONCLUSION